const vscode = require('vscode')
const path = require('path')

// test('activeTextEditor', eq => { })
// test('visibleTextEditors')
// test('state')
// test('terminals')

// test('onDidChangeActiveTextEditor')
// test('onDidChangeVisibleTextEditors')
// test('onDidChangeTextEditorSelection')
// test('onDidChangeTextEditorVisibleRanges')
// test('onDidChangeTextEditorOptions')
// test('onDidChangeTextEditorViewColumn')
// test('onDidOpenTerminal')
// test('onDidCloseTerminal')
// test('onDidChangeWindowState')

// test('createInputBox')
// test('createOutputChannel')
// test('createQuickPick')
// test('createStatusBarItem')
// test('createTerminal')
// test('createTextEditorDecorationType')
// test('createTreeView')
// test('createWebviewPanel')
// test('registerTreeDataProvider')
// test('registerUriHandler')
// test('registerWebviewPanelSerializer')
// test('setStatusBarMessage')
// test('showErrorMessage')
// test('showInformationMessage')
// test('showInputBox')
// test('showOpenDialog')
// test('showQuickPick')
// test('showSaveDialog')
// test('showTextDocument')
// test('showWarningMessage')
// test('showWorkspaceFolderPick')
// test('withProgress')
// test('withScmProgress')
